name = "MyExample"
uuid = "059bb350-0803-40ba-98ae-8cde44fad3f1"
authors = ["M.SAKSHAM"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
